name: "Deploy: Hello World"
on:
  push:
    branches: [ main ]
    paths:
      - 'src/HelloWorld/HelloWorld/**'
      
  workflow_dispatch:

jobs:
  setup-and-deploy:
    uses: IngridTPires/poc-git-actions/.github/workflows/functions-base.yml@main
    with:
      function_name: "hello-world"
      runtime: "dotnet6"
      entrypoint: "HelloWorld.Function"
      source_dir: "src/HelloWorld/HelloWorld"
      allow_unauthenticated: true
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_FUNCTION_SERVICE_ACCOUNT_KEY }}
