name: "Deploy: Hello World"
on:
  push:
    branches: [ main ]
    paths:
      - 'src/HelloWorld/HelloWorld/**'
      
  workflow_dispatch:

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    steps:    
      - id: 'checkout'
        uses: actions/checkout@v4

      - name: 'Deploy Base'
        uses: IngridTPires/poc-git-actionsX/.github/workflows/functions-base.yml@main
        with:
          function_name: "hello-world"
          runtime: "dotnet6"
          entrypoint: "HelloWorld.Function"
          source_dir: "src/HelloWorld/HelloWorld"
          allow_unauthenticated: true
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_FUNCTION_SERVICE_ACCOUNT_KEY }}
